#!/usr/bin/env python3
"""Verify every resource in the Indie Degree corpus actually exists, and is the
thing it claims to be.

A curriculum generated by an LLM is worthless if half its resources are
invented. HTTP 200 is not enough on its own — YouTube serves 200 for deleted
videos, and a renamed page still resolves. So each resource declares *how* it
can be identified, and we check the identity, not just the liveness:

    youtube / youtube_playlist   oEmbed  -> real title (404/400 when gone)
    arxiv                        arXiv API -> real title
    book                         OpenLibrary by ISBN -> real title
    github                       GitHub API -> full_name + description
    web                          GET -> status + a required literal substring
    pdf                          GET -> status + Content-Type is a PDF

`pdf` is deliberately the weakest check in the set: without a PDF parser we
can confirm a PDF is served at that URL but not that it is the right paper.
The method is recorded on every row, so a reader can see which guarantee they
are getting rather than having to assume.

The observed title is then compared against the claimed one. Hallucination
becomes a cheap string check instead of a leap of faith — the same move
Career Side Quests makes with verbatim evidence quotes.

Outcomes:
    verified         identity confirmed; goes into the corpus
    title_mismatch   the ref resolves but to something else; needs a human
    unverified       we were blocked or timed out; unknown, needs a human
    dead             the ref does not resolve; dropped from the corpus

Only `verified` rows are written to resources.verified.json. Everything else
lands in the report for review. Stdlib only, so there is nothing to install.

Usage:
    python scripts/corpus/verify.py
    python scripts/corpus/verify.py --no-cache          # re-check everything
    python scripts/corpus/verify.py --only karpathy-*   # check a subset
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from html import unescape
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CURRICULUM = ROOT / "src" / "products" / "curriculum"
SOURCE = CURRICULUM / "resources.json"
VERIFIED = CURRICULUM / "resources.verified.json"
REPORT = CURRICULUM / "verification-report.md"
CACHE = Path(__file__).parent / ".cache.json"

# Some hosts refuse anything that looks automated. A plain UA gets 403 from
# Coursera, DeepLearning.AI and a few university sites; those come back as
# `unverified` rather than `dead`, because "we were blocked" is not evidence
# of absence.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"
)
TIMEOUT = 25
WORKERS = 8

# arXiv rate-limits hard and answers a burst of parallel requests with a
# connection timeout, which looks exactly like a dead paper. Space them out.
ARXIV_MIN_INTERVAL = 6.0
_arxiv_lock = threading.Lock()
_arxiv_last = 0.0

# Below this token-overlap ratio the resolved resource is treated as a
# different thing from the one claimed.
TITLE_MATCH_THRESHOLD = 0.6

STOPWORDS = {
    "a", "an", "the", "of", "for", "and", "to", "in", "on", "with", "your",
    "from", "at", "by", "is", "it", "part", "vol", "edition", "ed",
}


# ---------------------------------------------------------------- http


def fetch(url: str, accept: str | None = None) -> tuple[int, str]:
    """GET a URL. Returns (status, body). Raises on transport failure."""
    headers = {"User-Agent": UA}
    if accept:
        headers["Accept"] = accept
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        charset = resp.headers.get_content_charset() or "utf-8"
        return resp.status, resp.read().decode(charset, errors="replace")


def fetch_json(url: str) -> Any:
    _, body = fetch(url, accept="application/json")
    return json.loads(body)


# ---------------------------------------------------------------- matching


def normalise(text: str) -> list[str]:
    text = unescape(text).lower()
    text = re.sub(r"[^a-z0-9\s]+", " ", text)
    return [t for t in text.split() if t and t not in STOPWORDS]


def titles_match(claimed: str, observed: str) -> tuple[bool, float]:
    """Token overlap of claimed against observed.

    Deliberately asymmetric: we ask how much of the *claimed* title is present
    in what we found. Observed titles are often longer ("... | Coursera",
    "Lecture 3 - ... (Autumn 2023)"), and that should not count against a
    match.
    """
    want, got = normalise(claimed), set(normalise(observed))
    if not want:
        return False, 0.0
    ratio = sum(1 for t in want if t in got) / len(want)
    return ratio >= TITLE_MATCH_THRESHOLD, round(ratio, 2)


def result(status: str, method: str, observed: str = "", detail: str = "",
           ratio: float | None = None, author: str = "") -> dict[str, Any]:
    out = {"status": status, "method": method}
    if observed:
        out["observed_title"] = observed
    # Who published it, straight from the source. For video especially, the
    # channel is the credibility signal — the same lecture re-uploaded by a
    # engagement-farming channel is not the same resource.
    if author:
        out["observed_author"] = author
    if detail:
        out["detail"] = detail
    if ratio is not None:
        out["title_match"] = ratio
    return out


# ---------------------------------------------------------------- checkers


def check_youtube(res: dict[str, Any]) -> dict[str, Any]:
    kind = res["type"]
    if kind == "youtube":
        target = f"https://www.youtube.com/watch?v={res['ref']}"
    else:
        target = f"https://www.youtube.com/playlist?list={res['ref']}"
    url = (
        "https://www.youtube.com/oembed?url="
        + urllib.parse.quote(target, safe="")
        + "&format=json"
    )
    data = fetch_json(url)
    observed = data.get("title", "")
    ok, ratio = titles_match(res["title"], observed)
    return result(
        "verified" if ok else "title_mismatch", "youtube-oembed", observed,
        ratio=ratio, author=data.get("author_name", ""),
    )


def check_arxiv(res: dict[str, Any]) -> dict[str, Any]:
    """Two independent paths to the same fact.

    The export API is the clean one but rate-limits aggressively and has been
    known to refuse an address outright for a while. The abs page carries a
    citation_title meta tag that says the same thing, so a corpus check does
    not fail merely because one endpoint is annoyed with us.
    """
    global _arxiv_last
    with _arxiv_lock:
        wait = ARXIV_MIN_INTERVAL - (time.monotonic() - _arxiv_last)
        if wait > 0:
            time.sleep(wait)
        _arxiv_last = time.monotonic()

    observed = ""
    method = "arxiv-api"
    try:
        _, body = fetch(f"http://export.arxiv.org/api/query?id_list={res['ref']}")
        # The first <title> is the query echo; the second is the paper.
        titles = re.findall(r"<title>(.*?)</title>", body, re.S)
        if len(titles) >= 2:
            observed = " ".join(unescape(titles[1]).split())
    except Exception:  # noqa: BLE001 - fall through to the second path
        pass

    if not observed:
        method = "arxiv-abs"
        _, body = fetch(f"https://arxiv.org/abs/{res['ref']}")
        m = re.search(r'<meta name="citation_title" content="(.*?)"', body)
        if not m:
            return result("dead", method, detail="no entry found for id")
        observed = " ".join(unescape(m.group(1)).split())

    ok, ratio = titles_match(res["title"], observed)
    return result(
        "verified" if ok else "title_mismatch", method, observed, ratio=ratio,
    )


def check_book(res: dict[str, Any]) -> dict[str, Any]:
    isbn = res["ref"].replace("-", "").strip()
    data = fetch_json(f"https://openlibrary.org/isbn/{isbn}.json")
    observed = data.get("title", "")
    if data.get("subtitle"):
        observed = f"{observed}: {data['subtitle']}"
    ok, ratio = titles_match(res["title"], observed)
    return result(
        "verified" if ok else "title_mismatch", "openlibrary-isbn", observed,
        ratio=ratio,
    )


def check_github(res: dict[str, Any]) -> dict[str, Any]:
    data = fetch_json(f"https://api.github.com/repos/{res['ref']}")
    observed = data.get("full_name", "")
    # Repos are identified by path, which we matched exactly by fetching it —
    # so the check is existence plus not-archived, not title similarity.
    detail = "archived" if data.get("archived") else ""
    status = "title_mismatch" if data.get("archived") else "verified"
    return result(status, "github-api", observed, detail=detail)


def check_web(res: dict[str, Any]) -> dict[str, Any]:
    """Fetch the page and require a literal substring to be present.

    `expect` is the load-bearing part. Without it this only proves a server
    answered, which is exactly the weak check we are trying to avoid.
    """
    expect = res.get("expect")
    if not expect:
        return result("unverified", "web", detail="no `expect` substring declared")
    status, body = fetch(res["ref"])
    haystack = unescape(body).lower()
    if expect.lower() in haystack:
        m = re.search(r"<title[^>]*>(.*?)</title>", body, re.S | re.I)
        observed = " ".join(unescape(m.group(1)).split()) if m else ""
        return result("verified", "web-substring", observed)
    return result(
        "title_mismatch", "web-substring",
        detail=f"expected substring not found: {expect!r}",
    )


def check_pdf(res: dict[str, Any]) -> dict[str, Any]:
    """Confirm a PDF is served at the URL. Cannot confirm which PDF."""
    req = urllib.request.Request(res["ref"], headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        ctype = resp.headers.get("Content-Type", "")
    if "pdf" not in ctype.lower():
        return result("title_mismatch", "pdf-contenttype",
                      detail=f"not a PDF (Content-Type: {ctype})")
    return result("verified", "pdf-contenttype",
                  detail="identity not checked — liveness only")


CHECKERS = {
    "youtube": check_youtube,
    "youtube_playlist": check_youtube,
    "arxiv": check_arxiv,
    "book": check_book,
    "github": check_github,
    "web": check_web,
    "pdf": check_pdf,
}

# A timeout is not evidence of absence, so transport failures get retried
# before we record anything about the resource. 429 counts as transport: it
# means we asked too fast, not that the paper is missing.
RETRIES = 3
RETRY_BACKOFF = 20.0


def check_once(res: dict[str, Any]) -> dict[str, Any]:
    checker = CHECKERS.get(res.get("type", ""))
    if not checker:
        return result("unverified", "none", detail=f"unknown type {res.get('type')!r}")
    try:
        return checker(res)
    except urllib.error.HTTPError as exc:
        # 404/400 on an identity endpoint means the thing is not there.
        # 401/403/429 mean we were refused or the item is private — a different
        # claim, and one a human has to settle.
        if exc.code in (401, 403, 429):
            return result("unverified", "http",
                          detail=f"HTTP {exc.code} (blocked or private)")
        return result("dead", "http", detail=f"HTTP {exc.code}")
    except Exception as exc:  # noqa: BLE001 - network is broad by nature
        return result("unverified", "http", detail=f"{type(exc).__name__}: {exc}")


def retryable(outcome: dict[str, Any]) -> bool:
    """Transport-shaped failures only — never a 401/403, which is a real answer."""
    if outcome["status"] != "unverified":
        return False
    detail = outcome.get("detail", "")
    return "429" in detail or "HTTP" not in detail


def check(res: dict[str, Any]) -> dict[str, Any]:
    outcome = check_once(res)
    for attempt in range(RETRIES):
        if not retryable(outcome):
            break
        time.sleep(RETRY_BACKOFF * (attempt + 1))
        outcome = check_once(res)
    return outcome


# ---------------------------------------------------------------- driver


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-cache", action="store_true")
    ap.add_argument("--only", default="*", help="glob over resource ids")
    ap.add_argument(
        "--retry-failed",
        action="store_true",
        help="re-check anything not currently verified (transport failures are "
             "cached like any other outcome, so a flaky host stays flagged)",
    )
    args = ap.parse_args()

    if not SOURCE.exists():
        print(f"no corpus at {SOURCE}", file=sys.stderr)
        return 1

    resources: list[dict[str, Any]] = json.loads(SOURCE.read_text("utf-8"))["resources"]
    cache = {} if args.no_cache or not CACHE.exists() else json.loads(
        CACHE.read_text("utf-8")
    )
    if args.retry_failed:
        cache = {k: v for k, v in cache.items() if v.get("status") == "verified"}

    todo = [r for r in resources if fnmatch.fnmatch(r["id"], args.only)]
    fresh = [r for r in todo if r["id"] not in cache]
    print(f"{len(resources)} resources · {len(todo)} selected · {len(fresh)} to check")

    if fresh:
        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            for res, verification in zip(fresh, pool.map(check, fresh)):
                cache[res["id"]] = verification
                flag = {"verified": "ok  ", "dead": "DEAD", "title_mismatch": "MISM",
                        "unverified": "??  "}[verification["status"]]
                print(f"  {flag} {res['id']}")
        CACHE.write_text(json.dumps(cache, indent=2), "utf-8")

    for res in resources:
        res["verification"] = cache.get(res["id"], result("unverified", "not-run"))

    verified = [r for r in resources if r["verification"]["status"] == "verified"]
    problems = [r for r in resources if r["verification"]["status"] != "verified"]

    VERIFIED.write_text(
        json.dumps(
            {
                "note": "Generated by scripts/corpus/verify.py. Do not edit by "
                        "hand — edit resources.json and re-run.",
                "verified_count": len(verified),
                "dropped_count": len(problems),
                "resources": verified,
            },
            indent=2,
            ensure_ascii=False,
        ),
        "utf-8",
    )

    lines = [
        "# Corpus verification report",
        "",
        f"- verified: **{len(verified)}**",
        f"- needs review: **{len(problems)}**",
        "",
    ]
    if problems:
        lines += ["| id | status | method | detail | observed |", "|---|---|---|---|---|"]
        for r in problems:
            v = r["verification"]
            lines.append(
                f"| `{r['id']}` | {v['status']} | {v.get('method','')} | "
                f"{v.get('detail','')} | {v.get('observed_title','')} |"
            )
    else:
        lines.append("Every resource verified.")
    REPORT.write_text("\n".join(lines) + "\n", "utf-8")

    print(f"\nverified {len(verified)} · needs review {len(problems)}")
    print(f"wrote {VERIFIED.relative_to(ROOT)} and {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
