import type { MetadataRoute } from "next";

/**
 * The web app manifest — the thing whose absence made Chrome offer "Create
 * shortcut" instead of "Install". A shortcut is a bookmark with an icon and
 * opens in a browser tab; an install needs a manifest declaring `display`
 * and icons, and only then does the launcher give it its own window.
 *
 * Icons are generated by icon.tsx and apple-icon.tsx, so there is no public/
 * directory to keep in step with the palette.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Indie Degree",
    // Launchers truncate around twelve characters and "Indie Degree" is exactly
    // twelve, which is close enough to the edge to come back as "Indie Degre…"
    // on some of them. "Indie" is unambiguous next to the other apps on this
    // home screen.
    short_name: "Indie",
    description:
      "Build your own degree, and prove you did it. A self-directed programme " +
      "where every source is identity-verified and every claim carries its evidence.",
    start_url: "/",
    display: "standalone",
    // Both from --background in globals.css. background_color fills the screen
    // while the app starts, so a value that disagrees with the page shows up as
    // a flash of the wrong colour on every launch. This app is light-only, so
    // there is no dark variant to reconcile.
    background_color: "#fdfdfc",
    theme_color: "#fdfdfc",
    // Deliberately unlocked, unlike the reading apps. The skill graph is
    // 1978px wide and scrolls inside its own container, and the calibration
    // table is a five-column grid — both are materially better in landscape,
    // and forcing portrait would be choosing a phone-shaped answer for a
    // transcript that is mostly read on a desktop.
    orientation: "any",
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
